// SPDX-License-Identifier: MIT
pragma solidity ^0.8.19;

/**
 * @title IZkTLSVerifier
 * @dev Interface for zkTLS proof verification (Primus zkTLS compatible)
 * @notice Verifies cryptographic proofs generated by Primus zkTLS attestations
 * 
 * The verifier validates that:
 * 1. The proof was generated by a valid Primus attestor
 * 2. The attested data (GISTDA portal response) is authentic
 * 3. The proof has not been tampered with
 */
interface IZkTLSVerifier {
    /**
     * @dev Verify a zkTLS attestation proof
     * @param proofHash The hash of the attestation data
     * @param signature The attestor's signature over the proof
     * @param attestorPublicKey The public key of the Primus attestor
     * @return verified True if the proof is valid
     */
    function verifyProof(
        bytes32 proofHash,
        bytes calldata signature,
        bytes calldata attestorPublicKey
    ) external view returns (bool verified);

    /**
     * @dev Verify a zkTLS attestation with full data
     * @param farmId The farm identifier from the attestation
     * @param noBurningDetected Whether the attestation shows no burning
     * @param timestamp The attestation timestamp
     * @param proofHash The hash of the attestation
     * @param signature The attestor's signature
     * @return verified True if the proof is valid and data matches
     */
    function verifyAttestation(
        string calldata farmId,
        bool noBurningDetected,
        uint256 timestamp,
        bytes32 proofHash,
        bytes calldata signature
    ) external view returns (bool verified);

    /**
     * @dev Check if an attestor public key is registered/valid
     * @param attestorPublicKey The public key to check
     * @return valid True if the attestor is authorized
     */
    function isValidAttestor(bytes calldata attestorPublicKey) external view returns (bool valid);
}
